stages:
  - publish

publish:
  stage: publish
  image: maven:3.8.8-eclipse-temurin-17
  script:
    - cat $MAVEN_SETTINGS
    - mvn deploy -s $MAVEN_SETTINGS
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .m2/repository
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+\-release/' # A specific tag with 'vX.Y.Z-release' pattern is created
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
    - when: never
#  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
#    tag_name: '$CI_COMMIT_TAG'
#    description: '$CI_COMMIT_TAG'
